//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlShortener.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class click
    {
        public int Id { get; set; }
        public string Referrer { get; set; }
        public string Agent { get; set; }
        public string Location { get; set; }
        public string Platform { get; set; }
        public System.DateTime DateTime { get; set; }
        public int UrlId { get; set; }
    }
}
