//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlShortener.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class url
    {
        public int Id { get; set; }
        public string OriginalUrl { get; set; }
        public string ShortenedSuffix { get; set; }
        public Nullable<long> UserId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
